mqtt_configs:
- broker: 127.0.0.1
  port: 1883
  client_id: mqtt_client_1
  username: "emqx"
  password: "emqx2024"
  nickname: "MQTTZ_1" # 别名用作查找的 Key，如果不存在则是用 {client_id}@{broker} 作为 Key
- broker: 127.0.0.1
  port: 1883
  client_id: mqtt_client_2
  username: "emqx"
  password: "emqx2024"
  nickname: "MQTTZ_2" # 别名用作查找的 Key，如果不存在则是用 {client_id}@{broker} 作为 Key