// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"MQTTZ/pkg/conf"
	"MQTTZ/pkg/mqtt"
	"MQTTZ/pkg/processor"
)

// Injectors from wire.go:

func InitializeMQTTZ() (*MQTTZ, error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, err
	}
	clientManager, err := mqtt.NewMQTTClientManager(config)
	if err != nil {
		return nil, err
	}
	validate := processor.NewValidate()
	mqttz := NewMQTTZ(config, clientManager, validate)
	return mqttz, nil
}
