name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  build:
    name: Build
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: MQTTZ-linux-amd64
          - os: windows-latest
            artifact_name: MQTTZ-windows-amd64.exe
          - os: macos-latest
            artifact_name: MQTTZ-darwin-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true

      - name: Build
        shell: bash
        run: |
          make clean
          make build
          mv ./bin/MQTTZ ./bin/${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./bin/${{ matrix.artifact_name }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/MQTTZ-linux-amd64
            ./artifacts/MQTTZ-windows-amd64.exe
            ./artifacts/MQTTZ-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}