name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]


jobs:
  build:
    name: Build
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: MQTTZ-linux-amd64
          - os: windows-latest
            artifact_name: MQTTZ-windows-amd64.exe
          - os: macos-latest
            artifact_name: MQTTZ-darwin-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true

      - name: Build
        shell: bash
        run: |
          make clean
          make build
          mv ./bin/MQTTZ ./bin/${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./bin/${{ matrix.artifact_name }}